Repository onosproject/onos-docs, pull requests merged in 2019-09, with the labels that each got.

#1 Add travis and mkdocs config files
  .gitignore
  .travis.yml
  build/build_docs.sh
  docs/README.md
  mkdocs.yml
Labels: WIP

#5 Add common documents to onos-docs
  docs/developers/community-info.md
  docs/developers/contributing.md
  docs/developers/dev_workflow.md
  docs/developers/prerequisites.md
Labels: documentation

#14 Adding instructions for authors
  README.md
  docs/developers/documentation.md
Labels: enhancement

#11 Fix some of the warnings to point to the correct links
  docs/developers/dev_workflow.md
  docs/developers/license_goland.md
  docs/developers/license_goland.txt
  docs/developers/prerequisites.md
  docs/developers/pull_requests.md
Labels: enhancement

#25 Adding link to README.md
  README.md
Labels: documentation
