Repository onosproject/onos-docs, pull requests merged in 2019-10, with the labels that each got.

#29 Adding links to the ONF Connect 2019 talks
  docs/README.md
Labels: enhancement

#30 Automate building docs locally and remotely and also improve its workflow
  .gitignore
  .travis.yml
  Makefile
  build/build_docs.sh
  docs/Makefile
  docs/check.Dockerfile
  docs/content/CNAME
  docs/content/README.md
  docs/content/developers/community-info.md
  docs/content/developers/contributing.md
  docs/content/developers/dev_workflow.md
  docs/content/developers/documentation.md
  docs/content/developers/license_goland.md
  docs/content/developers/license_goland.txt
  docs/content/developers/prerequisites.md
  docs/content/developers/pull_requests.md
  docs/content/images/contributing_workflow.png
  docs/content/images/uonos_architecture.png
  docs/docker-entrypoint.sh
  docs/docs.Dockerfile
  docs/mkdocs.yml
  docs/requirements.txt
  docs/scripts/lint.sh
  docs/scripts/verify.sh
  docs/theme/main.html
Labels: documentation, enhancement

#34 Added logo with transparency and text from onos website
  docs/content/images/onos_logo_2017.png
  docs/mkdocs.yml
Labels: enhancement

#36 Making 2017 logo square
  docs/content/images/onos_logo_2017.png
  docs/mkdocs.yml
Labels: bug

#40 Support versioning for onos-docs
  .gitignore
  .golangci.yml
  .travis.yml
  Makefile
  build/README.md
  build/docs-manager/Dockerfile
  build/licensing/boilerplate.generatego.txt
  build/licensing/boilerplate.go.txt
  build/licensing/boilerplate.proto.txt
  build/licensing/boilerplate.py
  build/licensing/boilerplate.py.txt
  cmd/README.md
  cmd/docs-manager/docs-manager.go
  docs/Makefile
  docs/configs/menu/onos-menu.css
  docs/configs/menu/onos-menu.js.gotmpl
  docs/configs/nav/nav_v0.1-onfconnect.yml
  docs/configs/nav/nav_v0.2.yml
  docs/configs/versions.yml
  docs/docker-entrypoint.sh
  docs/docs.Dockerfile
  docs/mkdocs.yml
  go.mod
  go.sum
  pkg/README.md
  pkg/build/build.go
  pkg/build/version-handler.go
  pkg/common/common.go
  pkg/manifest/manifest.go
  pkg/menu/css.go
  pkg/menu/js.go
  pkg/menu/manifest.go
  pkg/menu/menu.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
  pkg/types/types.go
  pkg/utils/util.go
  pkg/utils/yaml.go
  pkg/utils/yaml_test.go
Labels: enhancement

#42 Updating prerequisites with python3
  docs/content/developers/prerequisites.md
Labels: documentation

#44 Improve onos-docs build time
  .travis.yml
  pkg/build/version-handler.go
Labels: enhancement

#47 Add onos-docs-base image to reduce the build time
  Makefile
  build/base/Dockerfile
  build/docs-manager/Dockerfile
  docs/docs.Dockerfile
Labels: enhancement

#50 Optimize a little bit more the build process
  .travis.yml
  pkg/build/build.go
  pkg/build/version-handler.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
Labels: enhancement
