Repository onosproject/onos-docs, pull requests merged in 2020-01, with the labels that each got.

#96 Added a page on how to deploy on google cloud
  docs/configs/nav/nav_v0.2.yml
  docs/content/developers/deploy_on_gcp.md
  docs/content/images/cluster.png
  docs/content/images/services.png
Labels: enhancement

#98 Removing the onos-topo name override for config values.
  docs/content/developers/deploy_with_helm.md
Labels: bug

#99 Removed the file onos-gui/run.md
  docs/configs/nav/nav_v0.2.yml
Labels: documentation

#101 Updated the daily standup meeting link
  docs/content/developers/community-info.md
Labels: documentation
